apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: twinkle-ReplicaSet
  labels: 
    app: web
spec: #DEFINES THE BEHAVIOUR OF REPLICA SET
  replicas: 3
  selector: 
    matchLabels: 
      web: nginx
  template:
    metadata: 
      labels: 
        web: nginx
    spec: # DEFINES THE BEHAVIOUR OF THE POD
      containers: 
        - image: nginx
          name: nginx_container
          ports: 
            - containersport: 80



